### ISSUE TITLE
Relative dependencies?

### ISSUE THREAD

**Issue by dpeek** [explorigin/modular-js#1]
More of a question than an issue: I'm attempting a basic test using webpack, but it seems to expect modules to define relative dependencies. Seems simple enough to implement, just wondering if I'm doing something wrong :)

**Comment by explorigin** [comment]
Can you post your webpack.config.js and _.hxml file?

**Comment by dpeek** [comment]
Here's a minimal test:

`Test.hx`

``` haxe
class Test {
    static function main() {
        trace("foo");
    }
}
```

`build.hxml`

``` hxml
-main Test
-js gen/index.js
-lib modular-js
-cmd webpack
```

`webpack.config.js`

``` javascript
var path = require('path');

module.exports = {
  entry: './gen/index.js',
  output: {
    path: path.join(__dirname, 'bin'),
    filename: '[name].js',
    chunkFilename: 'chunk-[name].js'
  }
};
```

The basic problem is that the require paths should be relative, as webpack evaluates dependencies from the file that is requiring them. I've solved this in a branch, not sure if it's the best approach but will open a PR.

**Comment by explorigin** [comment]
I think this issue can be fixed by adding a `context` directive to your webpack.config file. http://webpack.github.io/docs/configuration.html#context

Something like `path.join(__dirname, 'gen')` should do it if you also change your entry to `'./index'`.
