### ISSUE TITLE
CommonJS Support

### ISSUE THREAD

**Issue by DavisDevelopment** [explorigin/modular-js#11]
Hey there. I've forked the project, and would love to add CommonJS support to my fork. I've been exploring the code, and it seems pretty easy to understand. I'm just posting this "issue" to both give you my props for having made such a neat library, and ask if you had any pointers to perhaps point me in the right direction towards adding said feature?
Thanks in advance.

**Comment by explorigin** [comment]
Thanks @DavisDevelopment. Checkout https://github.com/explorigin/modular-js/network.  Others have been working on this.
