### ISSUE TITLE
File not found error

### ISSUE THREAD

**Issue by xastor** [explorigin/modular-js#6]
When running a build I get this error : 

```
pieter$ haxe build.hxml 
/usr/local/lib/haxe/std/neko/_std/sys/io/File.hx:30: characters 20-51 : /usr/local/lib/haxe/lib/modular-js/js/enum_stub.js: No such file or directory
/usr/local/lib/haxe/lib/modular-js/0,9,1/src/modular/js/JsGenerator.hx:145: characters 3-64 : Called from
/usr/local/lib/haxe/lib/modular-js/0,9,1/src/modular/js/JsGenerator.hx:384: characters 3-40 : Called from
/usr/local/lib/haxe/lib/modular-js/0,9,1/src/modular/js/JsGenerator.hx:438: characters 46-77 : Called from
<null pos>:1: character 0 : Called from
Aborted
```

You can see that `/usr/local/lib/haxe/lib/modular-js/js/enum_stub.js` is not found, but when I look at the filesystem it seems that the root path to modular-js is incorrect because `/usr/local/lib/haxe/lib/modular-js/0,9,1/js/enum_stub.js` does exist.  

Is this a bug in modular-js?

**Comment by explorigin** [comment]
Does this solve your issue? https://github.com/explorigin/modular-js/pull/4  It's been some time since I worked with Haxe so I'm a bit rusty.

**Comment by xastor** [comment]
Yes, this PR solves by issue indeed, thanks!
