### ISSUE TITLE
Not working with Haxe 3.4

### ISSUE THREAD

**Issue by jcward** [explorigin/modular-js#8]
Compiling throws:
```
JsGenerator.hx:62: characters 2-30 : Invalid input value
<builtin>:1: character 0 : Called from
```

Seems to be a problem in Haxe, though. See my simplified testcase: https://github.com/HaxeFoundation/haxe/issues/5963

**Comment by explorigin** [comment]
Soooo, not an issue with this package?

**Comment by jcward** [comment]
Correct! It was fixed in Haxe about a week ago.
